config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :posts do
    collection do
      get 'list', action: :index_admin
    end
  end

  get 'tags/:tag', to: 'posts#index', as: :tag

  get 'dashboard' => 'admin#dashboard'

  root 'home#index'
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true, length: { minimum: 10, maximum: 255 }
  validates :body, presence: true

  acts_as_taggable

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!

  def dashboard
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'admin', only: [:new, :edit, :index_admin, :create, :update]
  before_action :authenticate_user!, only: [:new, :edit, :index_admin]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end

  def index_admin
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to list_posts_path, notice: 'Post was successfully created!'
    else
      render 'new'
    end
  end

  def update
    @post = Post.friendly.find(params[:id])

    if @post.update(post_params)
      redirect_to list_posts_path, notice: 'Post was successfully updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy

    redirect_to list_posts_path, notice: 'Post was successfully deleted!'
  end

  private

  def post_params
    params
      .required(:post)
        .permit(:title, :body, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard.html.haml
%h1 Welcome to dashboard

app/views/home/index.html.haml
- @posts.each do |post|
  %p #{link_to post.title, post} - #{post.created_at.strftime('%Y %B %d')}
  - post.tags.each do |tag|
    = link_to tag.name, tag_path(tag.name)
  %br

app/views/layouts/admin.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{:style => "padding-top: 70px"}
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Blog', dashboard_path, class: "navbar-brand"
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Post', list_posts_path
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to 'Edit account', edit_user_registration_path
            %li
              = link_to 'Logout', destroy_user_session_path, method: :delete
    .container
      - if notice.present?
        .alert.alert-info
          = notice
      - if alert.present?
        .alert.alert-danger
          = alert
      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container{:style => "padding-top: 70px"}
      %h1
        = link_to "Blog Name", root_url
      %br
      = yield

      %hr/
      %footer
        %p Copyright © Blog

app/views/posts/_form.html.haml
= form_for @post do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body
    = f.cktext_area :body, class: 'ckeditor'
  .form-group
    = f.label :tag_list, 'Tags (separated by commas)'
    = f.text_field :tag_list, value: @post.tags.join(', '), class: 'form-control tags'
  = f.submit

:javascript
  $('.tags').tagsInput();

app/views/posts/edit.html.haml
%h1 Edit Post

- if @post.errors.any?
  .alert.alert-danger
    - @post.errors.full_messages.each do |msg|
      = msg

= render "form"

app/views/posts/index.html.haml
- if params[:tag]
  %h3
    = "Tag: #{params[:tag]}"
- @posts.each do |post|
  %p #{link_to post.title, post} - #{post.created_at.strftime('%Y %B %d')}
  - post.tags.each do |tag|
    = link_to tag.name, tag_path(tag.name)
  %br

app/views/posts/index_admin.html.haml
%h1 Posts

= link_to 'New Post', new_post_path

%table.table
  %thead
    %tr
      %th #
      %th Title
      %th User
      %th Created at
      %th Updated at
      %th Actions
  %tbody
  - @posts.each do |post|
    %tr
      %th
        = post.id
      %td
        = post.title
      %td
        = post.user.email
      %td
        = post.created_at.strftime('%B %d, %Y')
      %td
        = post.updated_at.strftime('%B %d, %Y')
      %td
        = link_to 'Edit', edit_post_path(post)
        = link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/new.html.haml
%h1 New Post

- if @post.errors.any?
  .alert.alert-danger
    - @post.errors.full_messages.each do |msg|
      = msg

= render "form"

app/views/posts/show.html.haml
%h2.page-header
  = @post.title

%p
  = raw @post.body